---
language: python
sudo: required
dist: trusty
python:
  - 3.4

install:
  - pip install -r requirements.devel.txt
  - pip install codecov

script:
  - python setup.py lint
  - python setup.py test

after_success:
  - codecov
